### ISSUE TITLE
AIR SDK package remains downloaded after uninstalling

### ISSUE THREAD

**Issue by OMA2k** [airsdk/airsdkmanager-releases#1]
The AIRSDKManager app has an "AIR SDKs Location" field where you can set the directory where the AIR SDKs will be unpacked, but before unpacking, the whole AIR SDK package is downloaded somewhere unknown and remains there even after unpacking, because even if that particular AIR SDK is uninstalled using the interface, after clicking again on "Install", it will say "This install requires an estimated download of 0.00bytes", which means the package is already downloaded somewhere and the only thing it has to do to install it is unpacking it again.

So, where is this directory with downloaded packages located? This is not the "AIR SDKs Location" directory, because that contains the unpacked SDKs, not the downloaded packages.

**Comment by marchbold** [comment]
Hi,

There is a cache directory that AIR uses where all the components of the AIR SDK and airpackages from `apm` are stored. 

You can freely delete this at any time but will mean you'll have to completely redownload the whole sdk for any component updates.

The directory is located here:

```
[USER HOME]/.airsdk/cache/
```  

eg mine is `/Users/marchbold/.airsdk/cache/`

**Comment by OMA2k** [comment]
Thank you for the help. I've deleted the cache and I've tried redownloading the AIR 50.2.2 SDK again from the tool, but after installing it always says "checksum validation failed" every time. Is this a problem with my setup or with the package in the server? Version 50.2.1 seems to install without error, so the checksum error after installing 50.2.2 might be a problem with wrong files in the server or wrong checksum.

**Comment by marchbold** [comment]
Hi, There is an error with the api from harman reporting an incorrect checksum currently. You should be able to ignore this message as it's only for the release notes. We are resolving this issue in the next build hopefully in the next week.

**Comment by OMA2k** [comment]
Thank you for the help and the prompt replies!
