### ISSUE TITLE
Airsdk manager doesn't show anything on mac

### ISSUE THREAD

**Issue by shaymolho** [airsdk/airsdkmanager-releases#2]
![image (3)](https://github.com/airsdk/airsdkmanager-releases/assets/6802402/da0a6c82-e431-4ee4-b095-4d4a7f06d35a)
logs:
[airsdkmanager.log](https://github.com/airsdk/airsdkmanager-releases/files/13415713/airsdkmanager.log)

**Comment by marchbold** [comment]
Try setting the AIR SDKs location to where you plan to store the SDKs and then hitting refresh.

**Comment by shaymolho** [comment]
I already tried it but same result. did u look at the logs? the are exceptions there

**Comment by marchbold** [comment]
@shaymolho Can you try the latest release and see if this is still happening for you?

**Comment by shaymolho** [comment]
looks like latest version fixes this

**Comment by marchbold** [comment]
Thanks for confirming!
