### ISSUE TITLE
Import license keeps spinning forever on Mac Sonoma

### ISSUE THREAD

**Issue by PippoApps** [airsdk/airsdkmanager-releases#5]
Hello there,
I am trying to import my license on a Mac using AIRSDK Manager.
At import license, it just stays spinning forever.
It might be the license is expired since, after manually copying it into the lib folder, I still see the splash screen.
I have a few saved so I need to check which one is the active one.
On windows license import works perfectly.
<img width="732" alt="image" src="https://github.com/airsdk/airsdkmanager-releases/assets/29799572/3b7d4488-e2ac-4527-a203-c77ab09f31bf">
Cheers

**Comment by marchbold** [comment]
Thanks for reporting this. 

Can you confirm that the same license file works on windows but not on macOS? Does it work on other versions of macOS or have you only tested sonoma?

**Comment by PippoApps** [comment]
Hi,
It actually happens on Windows as well, with both expired and non-expired licenses.
Windows manager though already has a license set, while Mac one doesn't.
So either Harman license check server is down or they have some issue with my developer id I guess...
Does it work on your end reimporting a license?

**Comment by marchbold** [comment]
Hi, Yes it has been working on our end so not sure what's causing this. There is an update due out in a few weeks so just finalising that at the moment.

**Comment by PippoApps** [comment]
Thank you for checking this.
It's on Harman side then.
Cheers

**Comment by marchbold** [comment]
Could be, have you confirmed your license is still valid etc? Though even if it wasn't it should report this for you.

**Comment by marchbold** [comment]
The issue here has been identified and will be resolved in the next update.
