### ISSUE TITLE
The required native extension is missing for the application

### ISSUE THREAD

**Issue by Adolio** [airsdk/airsdkmanager-releases#6]
Hi @marchbold,

I get the following error when launching the new AIR SDK Manager (`v1.0.2`). I tried to re-install (uninstall + re-install) but it didn't work.

![Screenshot_2024-08-17_12-16-28](https://github.com/user-attachments/assets/439393fc-17f9-4e9b-a638-02b4a6d66c72)

Best,
Aurélien

**Comment by Policy56** [comment]
``` xml
<extensionID>androidx.core</extensionID>
<extensionID>com.distriqt.Notifications</extensionID>
<extensionID>com.distriqt.StatusBar</extensionID>
<extensionID>com.jetbrains.kotlin</extensionID>
```

has been added in the release code but not packaged in the *.msi installer.
It cannot be found in ${INSTALL_DIR}/META-INF/AIR/extensions


The workaround is to unzip the files in AISDKManager_1.0.2.pkg ( \Payload~\AIRSDKManager.app\Contents\Resource\META-INF\AIR\extensions ) and paste it in  ${INSTALL_DIR}/META-INF/AIR/extensions

**Comment by marchbold** [comment]
Hi, Thanks for reporting this, we'll look into it. Can you confirm the OS and version you are having this issue on.

**Comment by Adolio** [comment]
Hi @marchbold, 

Thanks for the answer. I tried to used the latest version `AIR SDK Manager v1.0.2` on Windows 10.

**Comment by marchbold** [comment]
Thanks, I've been able to replicate it and will look into the issue in the installer. In the meantime please install the previous version of the manager.

**Comment by Adolio** [comment]
Thanks for the update 👍

**Comment by marchbold** [comment]
This has been resolved , new build will be out soon
